<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Phone_ExtraInfo67</name>
   <tag></tag>
   <elementGuidId>e3198000-0551-4e91-983b-9f8e50ddaba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExtraInfo67</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ExtraInfo67']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Contact Phone&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc05e1cf-1a62-426c-b20f-8ce30668ce81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a9c3ccff-1512-4280-b60e-8f24d4e7e1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExtraInfo67</value>
      <webElementGuid>aed468c7-9767-44ec-bca0-9e346a505a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExtraInfo67</value>
      <webElementGuid>f21dd1bf-34f3-44f5-a55d-459670c3c0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datarecall</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f51246fd-3be5-4e8f-8ee2-4ff9e2a88a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mbrrecall</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e211624a-0864-47d2-b77f-f419d8f34988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>26de961e-6a0e-4b73-b249-8483873af542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>a4c559b8-f8ef-4cad-ae05-014ce85f58df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExtraInfo67&quot;)</value>
      <webElementGuid>95cbd7d3-e26f-49cf-987c-08d6d4a7f6d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExtraInfo67']</value>
      <webElementGuid>7e32cab0-0d08-4511-9311-065a0c8e9123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Row_ExtraInfo67']/div/div/div/input</value>
      <webElementGuid>c3ea8f9b-a701-4105-a86e-49f6c92ecdcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[6]/div[3]/div/div/div/input</value>
      <webElementGuid>05321cb1-40c6-428c-9855-fa0b4745b145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'ExtraInfo67' and @name = 'ExtraInfo67']</value>
      <webElementGuid>a4fdb1cf-4358-49cb-a9dd-3ee299c66681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
