<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I accept the Photography Waiver_ExtraInfo66</name>
   <tag></tag>
   <elementGuidId>52bf417c-686b-45d5-9241-7e13a4347e15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExtraInfo66</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ExtraInfo66']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;I accept the Photography Waiver.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75cf23da-7248-42c2-a644-d10f99126b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7f05cd22-768a-487d-83a5-a425a2328d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExtraInfo66</value>
      <webElementGuid>486c9c8a-ef8e-426b-919e-f1eea10061c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExtraInfo66</value>
      <webElementGuid>fae6e2ca-d9eb-4494-adf4-5a2f80b817a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datarecall</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>31f04dcd-568c-4065-8499-81a14091f0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mbrrecall</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bb4a09cf-8b44-46a9-a3f8-347ea3430dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>0e0f629b-d959-4a56-9cf8-2398ec9b05dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>9fc9e2ec-fb2c-415a-abf2-c61e5c704bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExtraInfo66&quot;)</value>
      <webElementGuid>3e218e60-64cd-40e9-a874-5cb33f4deebd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExtraInfo66']</value>
      <webElementGuid>d7fd55e5-2e37-4fd6-b434-e81ca78d3a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Row_ExtraInfo66']/div/div/label/input</value>
      <webElementGuid>9228c4a5-8341-4a63-a820-b6e65e7ddf14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/label/input</value>
      <webElementGuid>e8a04f00-48fb-406d-85c9-9ad2fb87239a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ExtraInfo66' and @name = 'ExtraInfo66']</value>
      <webElementGuid>35804647-7409-49c8-a84c-3a45c89ca337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
