<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_City</name>
   <tag></tag>
   <elementGuidId>d4f7e02f-aaf4-418c-beac-327d6f320808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#City</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='City']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;City&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ccc35052-3af8-4af4-abfb-54f2ce65981b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6694667b-a0fa-4917-92b7-b457bc24016e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>93b62a75-3be4-46b1-ac8c-ce62f48dccdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>a025f9d6-e991-4911-8121-2683941c794a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datarecall</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1fd42a31-5926-4e9e-8f42-2cb1a31d950a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mbrrecall</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>81f0c75e-4efc-4776-afbb-7baf343ea9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>201e7ef9-b822-4ca2-b1df-409ecaf303d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>e3730945-dba2-4626-9df6-a10b455599e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;City&quot;)</value>
      <webElementGuid>ace090ca-dec1-47af-9314-8aee70cbaeea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='City']</value>
      <webElementGuid>cb349d8e-7a12-4b1c-a764-0f5b91a01d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Row_City']/div/div/div/input</value>
      <webElementGuid>8f1c49e4-789d-4fd5-b854-2b8259fad48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>7b02a654-1989-4191-ae44-a28f543c4575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'City' and @name = 'City']</value>
      <webElementGuid>39535560-7ee2-4101-9e0a-2c46618f7946</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
