<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_Street</name>
   <tag></tag>
   <elementGuidId>dc2704d7-0a18-45c6-a127-c47ae73f780a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Street</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Street']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Address&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4cf9b60-8ba6-4c3e-9728-6553bee3ed17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce9359ac-67aa-42b4-a47c-ab4ea1956b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Street</value>
      <webElementGuid>2558b788-ce3d-4ac9-8bc1-7ad428e9d8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Street</value>
      <webElementGuid>cc7654fa-7566-457c-8a2e-14efcfa793d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datarecall</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c46b0194-1597-4057-b63e-252c603f80d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mbrrecall</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>19d65f06-073d-44f0-9c4d-5889ff8ac828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>41f59ad6-b04f-464f-81c5-b1a81e6983fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>4e2feeda-f792-4eca-b592-2c6210eee3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Street&quot;)</value>
      <webElementGuid>418e18de-bd04-491b-89ae-54fe19fd67de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Street']</value>
      <webElementGuid>b1837fae-8428-4b1b-9e3c-faceb44ff3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Row_Street']/div/div/div/input</value>
      <webElementGuid>6fafbec4-625a-47b3-8f6d-57ae9a070893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>28b6c095-3a20-45dd-a231-7ae4102b3cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Street' and @name = 'Street']</value>
      <webElementGuid>a0189833-3960-4fd7-94b0-d31ce72b9553</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
