<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Name_ExtraInfo65</name>
   <tag></tag>
   <elementGuidId>3b47fa73-70e6-42a4-8f53-5323ddc7ae3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExtraInfo65</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ExtraInfo65']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Contact Name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b65c0e62-8680-4f9a-8c13-98de49cf6b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8774f89-dee0-47a0-b5aa-d80459962d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExtraInfo65</value>
      <webElementGuid>1c9f5f91-5223-4cdb-a90c-ae9ceba7485a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExtraInfo65</value>
      <webElementGuid>a863f9d0-9d3d-492b-9f87-b1b5900bfa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datarecall</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>afd2d75e-8420-4f2c-829e-00a2a02edcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mbrrecall</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b7e89af1-bd5d-4145-9750-2f9dfd2f35af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3eb73f46-83b7-4b7b-8ab0-0a055b1028b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>ec3a041c-48fb-4b93-990f-3ef047aa032d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExtraInfo65&quot;)</value>
      <webElementGuid>13329f22-964b-4f72-8066-954b8e7cf5dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExtraInfo65']</value>
      <webElementGuid>88d184d8-d5de-4557-bd29-389b2f8eab16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Row_ExtraInfo65']/div/div/div/input</value>
      <webElementGuid>be386e13-4a12-46cc-8e40-8911697b3750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[6]/div[2]/div/div/div/input</value>
      <webElementGuid>2c1c3785-599c-49a5-b119-d198314719d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ExtraInfo65' and @name = 'ExtraInfo65']</value>
      <webElementGuid>d86e5282-cadf-442f-8193-de991ac4d9a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
