<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NPI Number_ExtraInfo70</name>
   <tag></tag>
   <elementGuidId>fa21c7c7-a22a-4226-ae95-b1246fb03c28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExtraInfo70</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ExtraInfo70']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;NPI Number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e032522-3617-412c-8f5e-06df6cd142d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a4f63ef-d33b-42e3-a727-4555b6b20a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExtraInfo70</value>
      <webElementGuid>46fde7f7-a31e-4f11-a67c-a1d92d4b2693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExtraInfo70</value>
      <webElementGuid>1ed8558b-a46c-47de-b397-6c90e28c0f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datarecall</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3da975fd-d733-4b40-934b-3e5d1a4923ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mbrrecall</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b098895-cec7-4a43-be13-209edb4f406f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b61a0314-1dcd-4e47-98c7-8ea51be62ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>c43595f1-d8b4-4dbb-a1cf-94170b804df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExtraInfo70&quot;)</value>
      <webElementGuid>80d2dabe-a029-4594-bf5e-d3a27c196c5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExtraInfo70']</value>
      <webElementGuid>18b40434-be15-4f2c-b961-ddd9eafc65fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Row_ExtraInfo70']/div/div/div/input</value>
      <webElementGuid>0a5d8e28-c833-4968-850b-20b1b72ebb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div[7]/div/div/div/input</value>
      <webElementGuid>3966cf6a-91a1-4c44-a8f8-9c6b52b25ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ExtraInfo70' and @name = 'ExtraInfo70']</value>
      <webElementGuid>ce22d437-97d7-450c-bc70-8791fd0019f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
