<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_In-Person Full Conference  Group Prof_fd7640</name>
   <tag></tag>
   <elementGuidId>500b48cb-4eaa-4cd4-9ea2-0d0da90a873a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#STRK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;In-Person Full Conference — Group Professional Attendee&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>291e20de-8fd1-4e6e-beef-568fe30ddd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>4913f12d-aca6-459b-b948-d1ac7a7d63d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8217d3a4-4938-4d22-9664-54da3ac078b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>STRK</value>
      <webElementGuid>21b56e70-af0e-435f-b661-7ec8eb4c93b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>STRK</value>
      <webElementGuid>6710c9cf-acac-4aca-b4a5-8602b5400a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>A|GROUP_STRK|7247</value>
      <webElementGuid>948fcb6c-8ead-4630-a219-cca607e60174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-packages</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fbd11360-f9be-453e-a1ed-d2eec4dd7379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemcode</name>
      <type>Main</type>
      <value>GROUP_STRK</value>
      <webElementGuid>f48d55ed-2596-4f3a-8ef7-ddc40485b4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promogroup</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d2dac7ae-ca8e-4020-b5a9-dc127ae0d2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pricekey</name>
      <type>Main</type>
      <value>7247</value>
      <webElementGuid>e6957a7a-5d42-4db4-9b9a-c7d12a1ed2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-currentprice</name>
      <type>Main</type>
      <value>995.00</value>
      <webElementGuid>96bd2d2f-75c4-4ae6-9b35-8a8eb4f8a842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-deselect</name>
      <type>Main</type>
      <value>#DAY,#WED,#THU,#FRI,#SAT,#SUN,#MON,#TUE,#STRK_SOD,#USB,#STRK_VIRTUAL,#SNS_V,#PRECON_1V,#PRECON_2V,#PRECON_3V</value>
      <webElementGuid>ba385f6e-75bf-4570-93ab-aa224353d74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-starttime</name>
      <type>Main</type>
      <value>2025-02-05 00:00:00</value>
      <webElementGuid>da6433e9-d919-43ab-acc6-d424034ba0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-endtime</name>
      <type>Main</type>
      <value>2025-02-07 00:00:00</value>
      <webElementGuid>f1bbeb5b-7a4d-403b-89a3-436e0889c5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;STRK&quot;)</value>
      <webElementGuid>0d46df9c-a993-4887-adc7-dbb5a3584f84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='STRK']</value>
      <webElementGuid>25c87ab6-d024-40cb-970a-ba47921ec8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='STRK_PackageText']/input</value>
      <webElementGuid>25c1ebab-636a-4a09-ae46-6c102db0bfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>523219c0-889e-4337-bb75-651e9729c5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'STRK' and @name = 'STRK']</value>
      <webElementGuid>3c82abb1-da5f-423c-9dc3-72602ad60f32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
