<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select                    CDSCDS</name>
   <tag></tag>
   <elementGuidId>a24f963a-1b61-4962-a020-75ab1f03e62c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OrderNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='OrderNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Company&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>95fdba8d-eabe-48ae-be52-a9b110a3aba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OrderNumber</value>
      <webElementGuid>aa04664a-5b6f-4ab0-9369-2fd8fa0e3512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OrderNumber</value>
      <webElementGuid>c9d74deb-ec6b-4b94-a131-7a8b39876a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datarecall</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>947e9141-4800-420c-a6f3-b1b8bbd3ef30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mbrrecall</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2f286f6f-c35c-48dd-987a-0b41e6714ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>a8da40d9-5d75-44b2-b3be-6007a9a7f7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Please Select
                    CDSCDS
                </value>
      <webElementGuid>5b949486-cbeb-4188-ab69-4a35b1a9deb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OrderNumber&quot;)</value>
      <webElementGuid>2aa7a102-a2c5-48f8-8d97-669b48f5eafb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='OrderNumber']</value>
      <webElementGuid>a37965b8-1b41-4a2e-8412-6fd09315e2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Row_OrderNumber']/div/div/div/select</value>
      <webElementGuid>3a0518bb-aa38-4899-ad37-3143d7c8cd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/following::select[1]</value>
      <webElementGuid>49628718-c2df-4ade-9b32-a4c34175bfc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='not'])[1]/following::select[1]</value>
      <webElementGuid>82d4a1b9-02c2-4523-bee6-ddf90b3fe9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::select[1]</value>
      <webElementGuid>c56cb606-d059-47ec-a8db-0301f64b32a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Important Information — Please Read:'])[1]/preceding::select[1]</value>
      <webElementGuid>ddca778d-1b83-42f8-90ad-fd0afca69e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e7394c64-74ce-428b-94b2-b4a5dd987e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'OrderNumber' and @name = 'OrderNumber' and (text() = '
                    Please Select
                    CDSCDS
                ' or . = '
                    Please Select
                    CDSCDS
                ')]</value>
      <webElementGuid>d1341ed7-efd5-4898-a5e8-39f52146687c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
